# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 545762b000ae0fd65cea85c50edb7907c1f639d28cc865643aebefa8d6b388fe76e1c5738ed2298b36eceb7396695ba843de7fd6347376237d812c1986ea482d

test:
  secret_key_base: 62f778df72c65781364809abac042c129b4eff7af3ceff3448dfb2f0d296d62a004f03349c11f87cf1d5b0d56810c8ae721b977754eab78c98f255c9aeeca9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
